import { useState, useEffect, useRef } from 'react';
import { X, Plus, Check, ExternalLink, FileBarChart2, Download, ArrowLeftRight, Loader2, BookOpen, Quote, Calendar, TrendingUp } from 'lucide-react';
import { getCatColor, fmtCit } from '../lib/colors';
import { api, type MicrotopicDetail, type Paper, type CompareRes, type GraphNode } from '../lib/api';

interface Props {
  microtopicId: string; allNodes: GraphNode[]; onClose: () => void;
  readingListIds: Set<string>; onAddToList: (id: string) => void; onRemoveFromList: (id: string) => void; userId: number;
}

export function MicrotopicPanel({ microtopicId, allNodes, onClose, readingListIds, onAddToList, onRemoveFromList }: Props) {
  const [detail, setDetail] = useState<MicrotopicDetail | null>(null);
  const [papers, setPapers] = useState<Paper[]>([]);
  const [paperTotal, setPaperTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<'papers' | 'report'>('papers');
  const [compareId, setCompareId] = useState('');
  const [compareData, setCompareData] = useState<CompareRes | null>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [papersPage, setPapersPage] = useState(1);
  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setLoading(true); setDetail(null); setPapers([]); setTab('papers'); setCompareData(null); setPapersPage(1);
    Promise.all([
      api.getMicrotopic(microtopicId),
      api.getMicrotopicPapers(microtopicId, { page: 1, per_page: 20, sort_by: 'citation_count' }),
    ]).then(([d, p]) => { setDetail(d); setPapers(p.papers); setPaperTotal(p.total); })
      .catch(() => {}).finally(() => setLoading(false));
  }, [microtopicId]);

  const loadMore = () => {
    const next = papersPage + 1;
    api.getMicrotopicPapers(microtopicId, { page: next, per_page: 20, sort_by: 'citation_count' })
      .then(p => { setPapers(prev => [...prev, ...p.papers]); setPapersPage(next); }).catch(() => {});
  };

  const runCompare = () => {
    if (!compareId) return;
    setReportLoading(true);
    api.compareMicrotopics(microtopicId, compareId).then(setCompareData).catch(() => setCompareData(null)).finally(() => setReportLoading(false));
  };

  useEffect(() => { if (compareId) setCompareData(null); }, [compareId]);

  const exportPDF = () => {
    if (!reportRef.current) return;
    const w = window.open('', '_blank'); if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>${detail?.label} Report</title>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=Instrument+Serif&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'DM Sans',system-ui;color:#1f2937;padding:32px;max-width:780px;margin:0 auto;font-size:11px}
    h1{font-family:'Instrument Serif',serif;font-size:22px}h2{font-size:10px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:.06em;margin:16px 0 6px}
    table{width:100%;border-collapse:collapse;margin:6px 0}th{text-align:left;padding:4px 6px;border-bottom:2px solid #e5e7eb;font-weight:600;color:#6b7280;font-size:8px;text-transform:uppercase}
    td{padding:4px 6px;border-bottom:1px solid #f3f4f6}.footer{margin-top:24px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:9px;color:#9ca3af}
    @media print{body{padding:16px}}</style></head><body>${reportRef.current.innerHTML}
    <div class="footer">Generated by ResearchViewer · ${new Date().toLocaleDateString()}</div></body></html>`);
    w.document.close(); setTimeout(() => w.print(), 500);
  };

  if (loading || !detail) return <div className="flex h-full items-center justify-center"><Loader2 size={20} className="animate-spin text-gray-400" /></div>;

  const cat = getCatColor(detail.bucket_value);
  const st = detail.stats;
  const otherNodes = allNodes.filter(n => n.id !== microtopicId);

  return (
    <div className="flex flex-col h-full">
      <div className="px-5 pt-5 pb-3 border-b border-gray-100 shrink-0">
        <div className="flex items-start justify-between gap-2 mb-2">
          <div className="flex-1 min-w-0">
            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold mb-1.5" style={{ backgroundColor: cat.fill, color: cat.text, border: `1px solid ${cat.border}40` }}>{detail.bucket_value}</span>
            <h2 className="text-base font-semibold text-gray-800 leading-snug">{detail.label}</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400"><X size={16} /></button>
        </div>
        <div className="grid grid-cols-4 gap-1.5">
          <MM icon={<BookOpen size={9} />} label="Papers" value={String(st.paper_count)} />
          <MM icon={<Quote size={9} />} label="Avg" value={fmtCit(st.avg_citations)} />
          <MM icon={<TrendingUp size={9} />} label="Total" value={fmtCit(st.total_citations)} />
          <MM icon={<Calendar size={9} />} label="Span" value={st.year_range || '—'} />
        </div>
        <div className="flex gap-1 mt-3">
          <button onClick={() => setTab('papers')} className={`flex-1 py-1.5 rounded-lg text-xs font-medium ${tab === 'papers' ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}>Papers ({paperTotal})</button>
          <button onClick={() => setTab('report')} className={`flex-1 py-1.5 rounded-lg text-xs font-medium flex items-center justify-center gap-1 ${tab === 'report' ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}><FileBarChart2 size={11} /> Report</button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        {tab === 'papers' && (
          <div className="px-5 py-3 space-y-1.5">
            {detail.top_terms && detail.top_terms.length > 0 && (
              <div className="flex flex-wrap gap-1 mb-2">
                {detail.top_terms.slice(0, 8).map(t => <span key={t} className="px-2 py-0.5 rounded-full text-[9px] font-medium bg-gray-100 text-gray-500">{t}</span>)}
              </div>
            )}
            {papers.map(p => {
              const inList = readingListIds.has(p.id);
              const arxiv = p.id.match(/^\d{4}\./) ? `https://arxiv.org/abs/${p.id}` : null;
              return (
                <div key={p.id} className="group p-2.5 rounded-lg border border-gray-100 hover:border-gray-200 hover:bg-gray-50/50">
                  <div className="flex items-start gap-2">
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-medium text-gray-700 leading-snug line-clamp-2">{p.title}</p>
                      <div className="flex items-center gap-2 mt-1 flex-wrap">
                        <span className="text-[9px] text-gray-400 font-mono">{p.id}</span>
                        <span className="text-[9px] text-gray-400">{fmtCit(p.citation_count)}</span>
                        {p.update_date && <span className="text-[9px] text-gray-400">{String(p.update_date).slice(0, 4)}</span>}
                      </div>
                    </div>
                    <div className="flex items-center gap-0.5 shrink-0">
                      {arxiv && <a href={arxiv} target="_blank" rel="noopener noreferrer" className="p-1 rounded text-gray-300 hover:text-gray-500 opacity-0 group-hover:opacity-100"><ExternalLink size={12} /></a>}
                      <button onClick={() => inList ? onRemoveFromList(p.id) : onAddToList(p.id)}
                        className={`p-1 rounded ${inList ? 'text-blue-500 bg-blue-50' : 'text-gray-300 hover:text-gray-500 opacity-0 group-hover:opacity-100'}`}>
                        {inList ? <Check size={12} /> : <Plus size={12} />}
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
            {papers.length < paperTotal && (
              <button onClick={loadMore} className="w-full py-2 text-xs text-gray-400 hover:text-gray-600">Load more ({paperTotal - papers.length} remaining)</button>
            )}
          </div>
        )}

        {tab === 'report' && (
          <div className="px-5 py-4">
            <div className="mb-3 flex items-center gap-2">
              <label className="text-[9px] font-semibold text-gray-400 uppercase shrink-0">Compare</label>
              <select value={compareId} onChange={e => setCompareId(e.target.value)} className="flex-1 px-2 py-1.5 rounded-lg border border-gray-200 text-xs bg-white focus:outline-none">
                <option value="">None</option>
                {otherNodes.map(n => <option key={n.id} value={n.id}>{n.label}</option>)}
              </select>
              {compareId && <button onClick={runCompare} disabled={reportLoading} className="px-2.5 py-1.5 rounded-lg bg-gray-800 text-white text-[10px] font-medium disabled:opacity-50"><ArrowLeftRight size={11} /></button>}
              <button onClick={exportPDF} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[10px] font-medium text-white bg-gray-800 shrink-0"><Download size={10} /> PDF</button>
            </div>
            {reportLoading && <div className="py-8 flex justify-center"><Loader2 size={20} className="animate-spin text-gray-400" /></div>}
            {!reportLoading && (
              <div ref={reportRef} className="space-y-4">
                <div>
                  <h1 style={{ fontFamily: "'Instrument Serif', serif", fontSize: '18px', color: '#1f2937' }}>{detail.label}</h1>
                  <p className="text-[10px] text-gray-400 mt-0.5">{detail.bucket_value} · {st.paper_count} papers · {new Date().toLocaleDateString()}</p>
                </div>
                {compareData ? (
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold" style={{ backgroundColor: cat.fill, color: cat.text }}>{detail.label}</span>
                      <ArrowLeftRight size={11} className="text-gray-400" />
                      <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-gray-100 text-gray-600">{compareData.topic_b.label}</span>
                    </div>
                    <table className="w-full text-xs"><thead><tr>
                      <th className="text-left py-1 px-2 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">Metric</th>
                      <th className="text-right py-1 px-2 text-[8px] uppercase border-b-2 border-gray-200" style={{ color: cat.text }}>{detail.label}</th>
                      <th className="text-right py-1 px-2 text-[8px] text-gray-500 uppercase border-b-2 border-gray-200">{compareData.topic_b.label}</th>
                    </tr></thead><tbody>
                      <CR label="Papers" a={st.paper_count} b={compareData.topic_b.stats.paper_count} />
                      <CR label="Total Cites" a={st.total_citations} b={compareData.topic_b.stats.total_citations} />
                      <CR label="Avg Cites" a={st.avg_citations} b={compareData.topic_b.stats.avg_citations} />
                      <CR label="Median" a={st.median_citations} b={compareData.topic_b.stats.median_citations} />
                      <CR label="Max" a={st.max_citations} b={compareData.topic_b.stats.max_citations} />
                    </tbody></table>
                    <div className="mt-3 p-2.5 rounded-lg bg-blue-50 border border-blue-200 text-xs text-blue-700">
                      {compareData.overlap.shared_paper_count} shared papers · {compareData.overlap.cross_citation_count} cross-cites · Jaccard {(compareData.overlap.jaccard_similarity * 100).toFixed(1)}%
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-4 gap-1.5">
                    <RC label="Papers" value={String(st.paper_count)} />
                    <RC label="Total" value={fmtCit(st.total_citations)} />
                    <RC label="Avg" value={fmtCit(st.avg_citations)} />
                    <RC label="Median" value={fmtCit(st.median_citations)} />
                    <RC label="Max" value={fmtCit(st.max_citations)} />
                    <RC label="Growth" value={`${Math.round(st.recent_growth_pct)}%`} />
                    <RC label="Span" value={st.year_range || '—'} />
                    <RC label="Authors" value={st.unique_author_count != null ? fmtCit(st.unique_author_count) : '—'} />
                  </div>
                )}
                {detail.papers_by_year.length > 0 && (<div>
                  <p className="text-[9px] font-semibold text-gray-400 uppercase mb-1.5">Citations by Year</p>
                  <SvgBar data={detail.papers_by_year.map(d => ({ label: d.year.toString().slice(-2), value: d.total_citations }))} color={cat.border} height={80} />
                </div>)}
                {detail.papers_by_year.length > 0 && (<div>
                  <p className="text-[9px] font-semibold text-gray-400 uppercase mb-1.5">Papers per Year</p>
                  <SvgBar data={detail.papers_by_year.map(d => ({ label: d.year.toString().slice(-2), value: d.count }))} color="#64748b" height={50} />
                </div>)}
                {detail.citation_distribution.length > 0 && (<div>
                  <p className="text-[9px] font-semibold text-gray-400 uppercase mb-1.5">Citation Distribution</p>
                  <div className="space-y-1">{detail.citation_distribution.map(d => {
                    const max = Math.max(...detail.citation_distribution.map(x => x.count), 1);
                    return (<div key={d.bucket} className="flex items-center gap-2">
                      <span className="w-16 text-right text-[9px] text-gray-500 font-mono shrink-0">{d.bucket}</span>
                      <div className="flex-1 h-3.5 bg-gray-100 rounded overflow-hidden"><div className="h-full rounded" style={{ width: `${(d.count / max) * 100}%`, backgroundColor: cat.border + 'cc' }} /></div>
                      <span className="w-8 text-[9px] text-gray-400 font-mono">{d.count}</span>
                    </div>);
                  })}</div>
                </div>)}
                {detail.top_papers.length > 0 && (<div>
                  <p className="text-[9px] font-semibold text-gray-400 uppercase mb-1.5">Top Papers</p>
                  <table className="w-full text-[10px]"><thead><tr>
                    <th className="text-left py-1 px-1 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">#</th>
                    <th className="text-left py-1 px-1 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">Title</th>
                    <th className="text-right py-1 px-1 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">Cites</th>
                  </tr></thead><tbody>
                    {detail.top_papers.slice(0, 8).map((p, i) => (
                      <tr key={p.id}><td className="py-1 px-1 text-gray-400 font-mono">{i + 1}</td>
                        <td className="py-1 px-1 text-gray-700 max-w-[220px] truncate">{p.title}</td>
                        <td className="py-1 px-1 text-right text-gray-600 font-mono">{fmtCit(p.citation_count)}</td></tr>))}
                  </tbody></table>
                </div>)}
                {detail.top_authors.length > 0 && (<div>
                  <p className="text-[9px] font-semibold text-gray-400 uppercase mb-1.5">Authors</p>
                  <div className="flex flex-wrap gap-1">{detail.top_authors.slice(0, 10).map(a => (
                    <span key={a.name} className="px-2 py-0.5 rounded-full text-[9px] font-medium bg-gray-100 text-gray-600 border border-gray-200">{a.name} ({a.paper_count})</span>
                  ))}</div>
                </div>)}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function MM({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (<div className="p-1.5 rounded-lg bg-gray-50 border border-gray-100 text-center">
    <div className="flex items-center justify-center gap-0.5 text-gray-400 mb-0.5">{icon}<span className="text-[7px] uppercase tracking-wider">{label}</span></div>
    <p className="text-xs font-bold text-gray-800 font-mono tabular-nums">{value}</p></div>);
}
function RC({ label, value }: { label: string; value: string }) {
  return (<div className="p-2 rounded-lg bg-gray-50 border border-gray-100"><p className="text-[7px] text-gray-400 uppercase">{label}</p><p className="text-sm font-bold text-gray-800 font-mono mt-0.5">{value}</p></div>);
}
function CR({ label, a, b }: { label: string; a: number; b: number }) {
  const w = a > b ? 'a' : b > a ? 'b' : '';
  return (<tr><td className="py-1 px-2 text-gray-600 text-xs">{label}</td>
    <td className={`py-1 px-2 text-right font-mono text-xs ${w === 'a' ? 'text-blue-600 font-semibold' : 'text-gray-500'}`}>{a.toLocaleString()}</td>
    <td className={`py-1 px-2 text-right font-mono text-xs ${w === 'b' ? 'text-blue-600 font-semibold' : 'text-gray-500'}`}>{b.toLocaleString()}</td></tr>);
}
function SvgBar({ data, color, height = 80 }: { data: { label: string; value: number }[]; color: string; height?: number }) {
  if (!data.length) return null;
  const max = Math.max(...data.map(d => d.value), 1);
  const bw = Math.max(8, Math.min(22, (340 - data.length * 2) / data.length));
  return (<div className="overflow-x-auto"><svg width={data.length * (bw + 3)} height={height + 18}>
    {data.map((d, i) => { const h2 = (d.value / max) * height; return (<g key={i}>
      <rect x={i * (bw + 3)} y={height - h2} width={bw} height={Math.max(h2, 1)} rx={2} fill={color} opacity={0.8} />
      <title>{d.label}: {d.value.toLocaleString()}</title>
      <text x={i * (bw + 3) + bw / 2} y={height + 12} textAnchor="middle" fontSize={7} fill="#9ca3af">{d.label}</text></g>); })}
  </svg></div>);
}
