import { useState, useRef } from 'react';
import { X, Plus, Check, ExternalLink, FileBarChart2, Download, ArrowLeftRight, Loader2, TrendingUp, BarChart3, BookOpen, Calendar, Quote } from 'lucide-react';
import { getCategoryColor, formatCitations } from '../lib/colors';
import { getPapersForTopic, type TopicNode, PAPER_CITATIONS, SEED_PAPERS } from '../lib/dummy-data';
import type { Paper } from '../lib/api';

interface Props {
  topic: TopicNode;
  allTopics: TopicNode[];
  onClose: () => void;
  readingList: string[];
  onAddToList: (doi: string) => void;
  onRemoveFromList: (doi: string) => void;
}

export function TopicDetailPanel({ topic, allTopics, onClose, readingList, onAddToList, onRemoveFromList }: Props) {
  const [tab, setTab] = useState<'papers' | 'report'>('papers');
  const [compareTopic, setCompareTopic] = useState('');
  const [reportReady, setReportReady] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const papers = getPapersForTopic(topic.id);
  const cat = getCategoryColor(topic.id);
  const readSet = new Set(readingList);
  const otherTopics = allTopics.filter(t => t.id !== topic.id);

  // Compute metrics
  const medianCitations = (() => {
    const sorted = papers.map(p => p.citation_count || 0).sort((a, b) => a - b);
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[mid] : Math.round((sorted[mid - 1] + sorted[mid]) / 2);
  })();
  const maxCitations = Math.max(...papers.map(p => p.citation_count || 0));
  const yearRange = (() => {
    const years = papers.map(p => p.update_date?.slice(0, 4)).filter(Boolean) as string[];
    if (!years.length) return '—';
    return `${Math.min(...years.map(Number))}–${Math.max(...years.map(Number))}`;
  })();
  const internalCitations = PAPER_CITATIONS.filter(c => {
    const topicDois = new Set(papers.map(p => p.doi));
    return topicDois.has(c.source) && topicDois.has(c.target);
  }).length;

  const generateReport = () => { setReportReady(true); setTab('report'); };

  const compareData = compareTopic ? (() => {
    const ct = allTopics.find(t => t.id === compareTopic);
    if (!ct) return null;
    const cp = getPapersForTopic(compareTopic);
    const cpMed = (() => { const s = cp.map(p => p.citation_count || 0).sort((a, b) => a - b); const m = Math.floor(s.length / 2); return s.length % 2 ? s[m] : Math.round((s[m - 1] + s[m]) / 2); })();
    return { topic: ct, papers: cp, medianCitations: cpMed, maxCitations: Math.max(...cp.map(p => p.citation_count || 0)) };
  })() : null;

  const exportPDF = () => {
    if (!reportRef.current) return;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>${topic.label} Report</title>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=Instrument+Serif&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'DM Sans',system-ui;color:#1f2937;padding:32px;max-width:780px;margin:0 auto;font-size:11px}
    h1{font-family:'Instrument Serif',serif;font-size:22px;margin-bottom:2px}h2{font-size:10px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:0.06em;margin:18px 0 6px}
    .subtitle{font-size:11px;color:#9ca3af;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}
    .card{padding:10px;border:1px solid #e5e7eb;border-radius:8px}.card-l{font-size:8px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.06em}
    .card-v{font-size:18px;font-weight:700;font-family:'JetBrains Mono',monospace;margin-top:2px}
    table{width:100%;border-collapse:collapse;margin:6px 0}th{text-align:left;padding:4px 6px;border-bottom:2px solid #e5e7eb;font-weight:600;color:#6b7280;font-size:8px;text-transform:uppercase;letter-spacing:0.06em}
    td{padding:4px 6px;border-bottom:1px solid #f3f4f6}svg{display:block;margin:4px 0}
    .comp{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:10px 0}.comp-col{padding:10px;border:1px solid #e5e7eb;border-radius:8px}
    .footer{margin-top:24px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:9px;color:#9ca3af}
    @media print{body{padding:16px}}</style></head><body>
    ${reportRef.current.innerHTML}
    <div class="footer">Generated by ResearchViewer · ${new Date().toLocaleDateString()}</div></body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 500);
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-5 pt-5 pb-4 border-b border-gray-100 shrink-0">
        <div className="flex items-start justify-between gap-2 mb-3">
          <div>
            <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold mb-2" style={{ backgroundColor: cat.fill, color: cat.text, border: `1px solid ${cat.border}40` }}>{topic.fullLabel}</span>
            <h2 className="text-lg font-semibold text-gray-800">{topic.label}</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-600 shrink-0 transition-colors"><X size={16} /></button>
        </div>
        {/* Key metrics */}
        <div className="grid grid-cols-4 gap-2">
          <MiniMetric icon={<BookOpen size={10} />} label="Papers" value={String(topic.paperCount)} />
          <MiniMetric icon={<Quote size={10} />} label="Avg Cites" value={formatCitations(topic.avgCitations)} />
          <MiniMetric icon={<TrendingUp size={10} />} label="Total Cites" value={formatCitations(topic.totalCitations)} />
          <MiniMetric icon={<Calendar size={10} />} label="Span" value={yearRange} />
        </div>

        {/* Tab switcher */}
        <div className="flex gap-1 mt-3">
          <button onClick={() => setTab('papers')} className={`flex-1 py-2 rounded-lg text-xs font-medium transition-all ${tab === 'papers' ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}>Papers ({papers.length})</button>
          <button onClick={() => { if (!reportReady) generateReport(); else setTab('report'); }} className={`flex-1 py-2 rounded-lg text-xs font-medium transition-all flex items-center justify-center gap-1.5 ${tab === 'report' ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}>
            <FileBarChart2 size={12} /> Report
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto">
        {tab === 'papers' && (
          <div className="px-5 py-3 space-y-1.5">
            {papers.map(p => {
              const isRead = readSet.has(p.doi);
              const arxiv = p.doi.match(/^\d{4}\./) ? `https://arxiv.org/abs/${p.doi}` : null;
              return (
                <div key={p.doi} className="group p-3 rounded-lg border border-gray-100 hover:border-gray-200 hover:bg-gray-50/50 transition-all">
                  <div className="flex items-start gap-2">
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-700 leading-snug line-clamp-2">{p.title}</p>
                      <div className="flex items-center gap-2 mt-1 flex-wrap">
                        <span className="text-[10px] text-gray-400 font-mono">{p.doi}</span>
                        <span className="text-[10px] text-gray-400">{formatCitations(p.citation_count)} cites</span>
                        {p.update_date && <span className="text-[10px] text-gray-400">{p.update_date.slice(0, 4)}</span>}
                      </div>
                      {p.authors && <p className="text-[10px] text-gray-400 mt-0.5 truncate">{p.authors}</p>}
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      {arxiv && <a href={arxiv} target="_blank" rel="noopener noreferrer" className="p-1.5 rounded-lg text-gray-300 hover:text-gray-500 hover:bg-gray-100 transition-colors opacity-0 group-hover:opacity-100"><ExternalLink size={13} /></a>}
                      <button onClick={() => isRead ? onRemoveFromList(p.doi) : onAddToList(p.doi)}
                        className={`p-1.5 rounded-lg transition-all ${isRead ? 'text-blue-500 bg-blue-50 hover:bg-blue-100' : 'text-gray-300 hover:text-gray-500 hover:bg-gray-100 opacity-0 group-hover:opacity-100'}`}>
                        {isRead ? <Check size={13} /> : <Plus size={13} />}
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {tab === 'report' && (
          <div className="px-5 py-4">
            {/* Compare selector */}
            <div className="mb-4 flex items-center gap-2">
              <label className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider shrink-0">Compare with</label>
              <select value={compareTopic} onChange={e => setCompareTopic(e.target.value)}
                className="flex-1 px-2.5 py-1.5 rounded-lg border border-gray-200 text-xs text-gray-700 bg-white focus:outline-none focus:ring-1 focus:ring-gray-300">
                <option value="">No comparison</option>
                {otherTopics.map(t => <option key={t.id} value={t.id}>{t.label} ({t.fullLabel})</option>)}
              </select>
              <button onClick={exportPDF} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[10px] font-medium text-white bg-gray-800 hover:bg-gray-700 transition-all shrink-0">
                <Download size={11} /> PDF
              </button>
            </div>

            <div ref={reportRef} className="space-y-5">
              {/* Report title */}
              <div>
                <h1 style={{ fontFamily: "'Instrument Serif', serif", fontSize: '20px', color: '#1f2937' }}>{topic.label} — Analytics Report</h1>
                <p className="text-[11px] text-gray-400 mt-0.5">{topic.fullLabel} · {topic.paperCount} papers · Generated {new Date().toLocaleDateString()}</p>
              </div>

              {/* Metrics grid */}
              {compareData ? (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold" style={{ backgroundColor: cat.fill, color: cat.text }}>{topic.label}</span>
                    <ArrowLeftRight size={12} className="text-gray-400" />
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold" style={{ backgroundColor: getCategoryColor(compareTopic).fill, color: getCategoryColor(compareTopic).text }}>{compareData.topic.label}</span>
                  </div>
                  <table className="w-full text-xs">
                    <thead><tr>
                      <th className="text-left py-1.5 px-2 text-[9px] text-gray-400 uppercase tracking-wider border-b-2 border-gray-200">Metric</th>
                      <th className="text-right py-1.5 px-2 text-[9px] uppercase tracking-wider border-b-2 border-gray-200" style={{ color: cat.text }}>{topic.label}</th>
                      <th className="text-right py-1.5 px-2 text-[9px] uppercase tracking-wider border-b-2 border-gray-200" style={{ color: getCategoryColor(compareTopic).text }}>{compareData.topic.label}</th>
                    </tr></thead>
                    <tbody>
                      <CompRow label="Paper Count" a={topic.paperCount} b={compareData.topic.paperCount} />
                      <CompRow label="Total Citations" a={topic.totalCitations} b={compareData.topic.totalCitations} />
                      <CompRow label="Avg Citations" a={topic.avgCitations} b={compareData.topic.avgCitations} />
                      <CompRow label="Median Citations" a={medianCitations} b={compareData.medianCitations} />
                      <CompRow label="Max Citations" a={maxCitations} b={compareData.maxCitations} />
                      <CompRow label="Recent Growth" a={Math.round(topic.recentGrowth * 100)} b={Math.round(compareData.topic.recentGrowth * 100)} suffix="%" />
                    </tbody>
                  </table>

                  {/* Side-by-side citation timelines */}
                  <p className="text-[9px] font-semibold text-gray-400 uppercase tracking-wider mt-4 mb-2">Citations Over Time</p>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-3 rounded-lg border border-gray-100">
                      <p className="text-[9px] font-medium text-gray-500 mb-1">{topic.label}</p>
                      <BarChart data={topic.citationsOverTime.map(d => ({ label: d.year.slice(2), value: d.citations }))} color={cat.border} height={80} />
                    </div>
                    <div className="p-3 rounded-lg border border-gray-100">
                      <p className="text-[9px] font-medium text-gray-500 mb-1">{compareData.topic.label}</p>
                      <BarChart data={compareData.topic.citationsOverTime.map(d => ({ label: d.year.slice(2), value: d.citations }))} color={getCategoryColor(compareTopic).border} height={80} />
                    </div>
                  </div>
                </div>
              ) : (
                <>
                  <div className="grid grid-cols-4 gap-2">
                    <ReportCard label="Papers" value={String(topic.paperCount)} />
                    <ReportCard label="Total Cites" value={formatCitations(topic.totalCitations)} />
                    <ReportCard label="Avg Cites" value={formatCitations(topic.avgCitations)} />
                    <ReportCard label="Median Cites" value={formatCitations(medianCitations)} />
                    <ReportCard label="Max Cites" value={formatCitations(maxCitations)} />
                    <ReportCard label="Internal Links" value={String(internalCitations)} />
                    <ReportCard label="Recent Growth" value={`${Math.round(topic.recentGrowth * 100)}%`} />
                    <ReportCard label="Year Range" value={yearRange} />
                  </div>

                  {/* Citations over time chart */}
                  <div>
                    <p className="text-[9px] font-semibold text-gray-400 uppercase tracking-wider mb-2">Total Citations by Year</p>
                    <BarChart data={topic.citationsOverTime.map(d => ({ label: d.year.slice(2), value: d.citations }))} color={cat.border} height={100} />
                  </div>

                  {/* Papers per year */}
                  <div>
                    <p className="text-[9px] font-semibold text-gray-400 uppercase tracking-wider mb-2">Papers Published by Year</p>
                    <BarChart data={topic.citationsOverTime.map(d => ({ label: d.year.slice(2), value: d.count }))} color="#64748b" height={60} />
                  </div>

                  {/* Citation distribution */}
                  <div>
                    <p className="text-[9px] font-semibold text-gray-400 uppercase tracking-wider mb-2">Citation Distribution</p>
                    <div className="space-y-1">
                      {(() => {
                        const buckets = [
                          { label: '100k+', min: 100000 }, { label: '50k–100k', min: 50000, max: 100000 },
                          { label: '10k–50k', min: 10000, max: 50000 }, { label: '1k–10k', min: 1000, max: 10000 },
                          { label: '<1k', min: 0, max: 1000 },
                        ];
                        const max = Math.max(...buckets.map(b => papers.filter(p => (p.citation_count || 0) >= b.min && (!b.max || (p.citation_count || 0) < b.max)).length), 1);
                        return buckets.map(b => {
                          const count = papers.filter(p => (p.citation_count || 0) >= b.min && (!b.max || (p.citation_count || 0) < b.max)).length;
                          return (
                            <div key={b.label} className="flex items-center gap-2">
                              <span className="w-16 text-right text-[10px] text-gray-500 font-mono shrink-0">{b.label}</span>
                              <div className="flex-1 h-4 bg-gray-100 rounded overflow-hidden">
                                <div className="h-full rounded" style={{ width: `${(count / max) * 100}%`, backgroundColor: cat.border + 'cc' }} />
                              </div>
                              <span className="w-6 text-[10px] text-gray-400 font-mono">{count}</span>
                            </div>
                          );
                        });
                      })()}
                    </div>
                  </div>
                </>
              )}

              {/* Top papers table */}
              <div>
                <p className="text-[9px] font-semibold text-gray-400 uppercase tracking-wider mb-2">Top Papers by Citations</p>
                <table className="w-full text-xs">
                  <thead><tr>
                    <th className="text-left py-1.5 px-2 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">#</th>
                    <th className="text-left py-1.5 px-2 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">Title</th>
                    <th className="text-right py-1.5 px-2 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">Year</th>
                    <th className="text-right py-1.5 px-2 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">Citations</th>
                    <th className="text-right py-1.5 px-2 text-[8px] text-gray-400 uppercase border-b-2 border-gray-200">% of Total</th>
                  </tr></thead>
                  <tbody>
                    {papers.slice(0, 8).map((p, i) => (
                      <tr key={p.doi} className="hover:bg-gray-50">
                        <td className="py-1.5 px-2 text-gray-400 font-mono">{i + 1}</td>
                        <td className="py-1.5 px-2 text-gray-700 max-w-[200px] truncate">{p.title}</td>
                        <td className="py-1.5 px-2 text-right text-gray-500 font-mono">{p.update_date?.slice(0, 4)}</td>
                        <td className="py-1.5 px-2 text-right text-gray-600 font-mono font-medium">{formatCitations(p.citation_count)}</td>
                        <td className="py-1.5 px-2 text-right text-gray-400 font-mono">{topic.totalCitations > 0 ? Math.round(((p.citation_count || 0) / topic.totalCitations) * 100) : 0}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Key authors */}
              <div>
                <p className="text-[9px] font-semibold text-gray-400 uppercase tracking-wider mb-2">Prolific Authors</p>
                <div className="flex flex-wrap gap-1.5">
                  {(() => {
                    const authorCounts = new Map<string, number>();
                    for (const p of papers) {
                      for (const a of (p.authors || '').split(',').map(s => s.trim()).filter(Boolean).slice(0, 3)) {
                        authorCounts.set(a, (authorCounts.get(a) || 0) + 1);
                      }
                    }
                    return Array.from(authorCounts.entries()).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([name, count]) => (
                      <span key={name} className="px-2 py-0.5 rounded-full text-[10px] font-medium bg-gray-100 text-gray-600 border border-gray-200">
                        {name} <span className="text-gray-400 font-mono">({count})</span>
                      </span>
                    ));
                  })()}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Sub-components ───────────────────────────────────────────

function MiniMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="p-2 rounded-lg bg-gray-50 border border-gray-100 text-center">
      <div className="flex items-center justify-center gap-1 text-gray-400 mb-0.5">{icon}<span className="text-[8px] uppercase tracking-wider">{label}</span></div>
      <p className="text-sm font-bold text-gray-800 font-mono tabular-nums">{value}</p>
    </div>
  );
}

function ReportCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="p-2.5 rounded-lg bg-gray-50 border border-gray-100">
      <p className="text-[8px] text-gray-400 uppercase tracking-wider">{label}</p>
      <p className="text-base font-bold text-gray-800 font-mono tabular-nums mt-0.5">{value}</p>
    </div>
  );
}

function CompRow({ label, a, b, suffix = '' }: { label: string; a: number; b: number; suffix?: string }) {
  const w = a > b ? 'a' : b > a ? 'b' : 'tie';
  return (
    <tr>
      <td className="py-1.5 px-2 text-gray-600 text-xs">{label}</td>
      <td className={`py-1.5 px-2 text-right font-mono tabular-nums text-xs ${w === 'a' ? 'text-blue-600 font-semibold' : 'text-gray-500'}`}>{a.toLocaleString()}{suffix}</td>
      <td className={`py-1.5 px-2 text-right font-mono tabular-nums text-xs ${w === 'b' ? 'text-blue-600 font-semibold' : 'text-gray-500'}`}>{b.toLocaleString()}{suffix}</td>
    </tr>
  );
}

function BarChart({ data, color, height = 80 }: { data: { label: string; value: number }[]; color: string; height?: number }) {
  if (!data.length) return <p className="text-[10px] text-gray-400 italic">No data</p>;
  const max = Math.max(...data.map(d => d.value), 1);
  const barW = Math.max(8, Math.min(24, (300 - data.length * 2) / data.length));
  const totalW = data.length * (barW + 3);
  return (
    <div className="overflow-x-auto">
      <svg width={Math.max(totalW, 100)} height={height + 20} className="block">
        {data.map((d, i) => {
          const barH = (d.value / max) * height;
          const x = i * (barW + 3);
          return (
            <g key={i}>
              <rect x={x} y={height - barH} width={barW} height={Math.max(barH, 1)} rx={2} fill={color} opacity={0.8} />
              <title>{d.label}: {d.value.toLocaleString()}</title>
              <text x={x + barW / 2} y={height + 12} textAnchor="middle" fontSize={8} fill="#9ca3af" fontFamily="'JetBrains Mono', monospace">{d.label}</text>
            </g>
          );
        })}
      </svg>
    </div>
  );
}
